### ISSUE TITLE
[Feature]: Loading animation

### ISSUE THREAD

**Issue by MartinX3** [DerYeger/vue2-masonry-wall#35] opened 2022-08-02 14:51 UTC
### Description

The masonry walls misses a loading animation.

For now if there are many pictures the `v-dialog` doesn't appear until a few pictures are loaded and it seems that the application is frozen.

### Solution

It would be nice if pictures which are still being loaded are replaced by the [v-skeleton-loader](https://vuetifyjs.com/en/components/skeleton-loaders/) until they are downloaded.

The skeleton width could be determined by the template element width and the `column-width`.

Or maybe a `onFinish` event would be nice, then I could develop something myself.
But a builtin solution would reduce the amount of code.

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment] 2022-08-02 14:56
Your questions seems to be concerned with specific Vuetify components.

This library does not handle presentation, only the layout of its elements.
If you require a skeleton loader, wrap the images in a custom component.

**Comment by MartinX3** [comment] 2022-08-02 15:06
Hmm, I tried it with the placeholder inside the `v-img` but somehow the v-dialog still needs a bit to appear and later loaded pictures just "pop in" the wall. They appear out of nowhere without the animation.
That confuses me.

```
<template #placeholder>
	  <v-sheet>
		  <v-skeleton-loader width="100%" />
	  </v-sheet>
</template>
```

**Comment by DerYeger** [comment] 2022-08-02 15:11
This seems to be an issue with Vuetify, not this library.

**Comment by MartinX3** [comment] 2022-08-02 15:14
Nice to know, thank you.
I hope it's not a vue 2.7 issue with the new setup composition api.

**Comment by DerYeger** [comment] 2022-08-02 15:35
> I simulated a slow internet connection and saw that it waits until the first image is loaded until it shows she skeletons / elements of the other items I gave the masonry-wall element.
> I'm unsure if it's a vue(tify) issue or something with my code base or this project.

I need a minimal reproducible example to investigate this issue.

**Comment by MartinX3** [comment] 2022-08-02 17:54
https://codesandbox.io/s/vuetify-2-forked-4r4vb8?file=/src/App.vue

I hope it is minimal enough.

I think the masonry-wall element kills the lazy loading of the v-img.
It should only load the images I can see in the viewport, but I see 272 requests for the 451 pictures at the beginning.
Probably because how the masonry-wall sorts the pictures it puts many of them into the view of the browser before it pushes them down out of the viewport.

**Comment by MartinX3** [comment] 2022-08-02 18:03
In my own project I also tried it with a <v-row> <v-col> approach.
`masonry-wall` -> 63 requests
`<v-row> <v-col>` -> 42 requests

Maybe it's possible to optimize the `masonry-wall` to trigger less `v-img` loadings at the beginning.

**Comment by DerYeger** [comment] 2022-08-02 21:29
> https://codesandbox.io/s/vuetify-2-forked-4r4vb8?file=/src/App.vue
> 
> I hope it is minimal enough.
> 
> I think the masonry-wall element kills the lazy loading of the v-img. It should only load the images I can see in the viewport, but I see 272 requests for the 451 pictures at the beginning. Probably because how the masonry-wall sorts the pictures it puts many of them into the view of the browser before it pushes them down out of the viewport.

This can be fixed by ensuring that the Vuetify components actually have a height, as they seem to render with a height of 0 be default. See https://codesandbox.io/s/vuetify-2-forked-d4bpme?file=/src/App.vue.

However, there's something wrong with the `v-img`. as mounting it takes a huge amount of time.

**Comment by DerYeger** [comment] 2022-08-02 21:30
> In my own project I also tried it with a approach. `masonry-wall` -> 63 requests `<v-row> <v-col>` -> 42 requests
> 
> Maybe it's possible to optimize the `masonry-wall` to trigger less `v-img` loadings at the beginning.

Requests shouldn't be an issue, since the browser caches the result if the appropriate headers for static content such as images are set.

**Comment by MartinX3** [comment] 2022-08-02 23:02
> This can be fixed by ensuring that the Vuetify components actually have a height, as they seem to render with a height of 0 be default. See [codesandbox.io/s/vuetify-2-forked-d4bpme?file=/src/App.vue](https://codesandbox.io/s/vuetify-2-forked-d4bpme?file=/src/App.vue).
> 
> However, there's something wrong with the `v-img`. as mounting it takes a huge amount of time.

Thank you, that worked. Now it loads less at once.

Indeed, it's weird. But they claim that it's just an extended `<img>`.
I hope vuetify 3 will be faster.

**Comment by MartinX3** [comment] 2022-08-02 23:04
> > In my own project I also tried it with a approach. `masonry-wall` -> 63 requests `<v-row> <v-col>` -> 42 requests
> > Maybe it's possible to optimize the `masonry-wall` to trigger less `v-img` loadings at the beginning.
> 
> Requests shouldn't be an issue, since the browser caches the result if the appropriate headers for static content such as images are set.

Hmm, yes, it should be vuetify consuming too much cpu cycles rendering many empty v-img in a dialog.

**Comment by MartinX3** [comment] 2022-08-03 08:37
I made 2 codesandbox examples and somehow the masonry-wall example takes much longer than the v-row/v-col example.
Do you know why?

`masonry-wall`
https://codesandbox.io/s/masonry-wall-img-dialog-performance-4r4vb8
`v-row/v-col`
https://codesandbox.io/s/img-dialog-performance-ze6hnj

**Closed** 2022-08-08 20:31 UTC
Labels: enhancement
